-- 1. Total Revenue

SELECT
SUM(Total_Sales) AS Total_Revenue
FROM sales;

-- 2. Total Number of Orders

SELECT
COUNT(Order_ID) AS Total_Orders
FROM sales;

-- 3. Total Customers

SELECT
COUNT(DISTINCT Customer_ID) AS Total_Customers
FROM sales;


-- 4. Top 5 Products by Revenue

SELECT
Product,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 5;

-- 5. Top Categories by Revenue

SELECT
Category,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY Category
ORDER BY Revenue DESC;

-- 6. Revenue by City

SELECT
City,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY City
ORDER BY Revenue DESC;

-- 7. Top 10 Customers by Revenue

SELECT
Customer_Name,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY Customer_Name
ORDER BY Revenue DESC
LIMIT 10;

-- 8. Average Sales by Gender

SELECT
Gender,
ROUND(AVG(Total_Sales),2) AS Average_Sales
FROM sales
GROUP BY Gender;

-- 9. Most Sold Products

SELECT
Product,
SUM(Quantity) AS Quantity_Sold
FROM sales
GROUP BY Product
ORDER BY Quantity_Sold DESC;

-- 10. Monthly Revenue Trend

SELECT
strftime('%Y-%m', Order_Date) AS Month,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY Month
ORDER BY Month;

-- 11. Average Customer Age by Category

SELECT
Category,
ROUND(AVG(Age),2) AS Average_Age
FROM sales
GROUP BY Category
ORDER BY Average_Age DESC;

-- 12. Revenue Generated by Gender

SELECT
Gender,
SUM(Total_Sales) AS Revenue
FROM sales
GROUP BY Gender;

-- 13. Top 5 Cities by Orders

SELECT
City,
COUNT(Order_ID) AS Total_Orders
FROM sales
GROUP BY City
ORDER BY Total_Orders DESC
LIMIT 5;


-- 14. Highest Single Orders

SELECT
Order_ID,
Customer_Name,
Product,
Total_Sales
FROM sales
ORDER BY Total_Sales DESC
LIMIT 10;


-- 15. Category-wise Quantity Sold

SELECT
Category,
SUM(Quantity) AS Quantity_Sold
FROM sales
GROUP BY Category
ORDER BY Quantity_Sold DESC;